// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#include "../ui.h"

void ui_QRcode_screen_init(void)
{
    ui_QRcode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QRcode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_QRcode);
    lv_img_set_src(ui_Image2, &ui_img_download_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 35);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
