// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#include "ui.h"
// #include "board.h"
// #include "application.h"
// #include "audio_codec.h"
void ChangeVolumn(lv_event_t * e)
{
	// Your code here
	// auto &board = Board::GetInstance();
	// board.GetAudioCodec()->SetOutputVolume((int)lv_slider_get_value(ui_volumn));
	// (int)lv_slider_get_value(ui_volumn);
}

void ClickeWake(lv_event_t * e)
{
	// Your code here
}

void ClickeDelNetSet(lv_event_t * e)
{
	// Your code here
}

void checkBatColor(lv_event_t * e)
{
	// Your code here
}
